Hamzanael/update pom version
ExpediaGroup/openworld-sdk-java-generators pull request #3
Opened 2022-08-24 21:15 UTC by Hamzanael

### :pencil: Description

Changes that are needed for releasing to the maven central

2022-08-25 11:08 UTC, mohnoor94 requested changes

2022-08-25 11:08 UTC, mohnoor94 commented on openapi/src/main/kotlin/com/expediagroup/sdk/generators/openapi/OpenApiSdkGenerator.kt
> +                val createTempFile = Files.createTempFile("", ".yaml")
(naming): `inputFile`, `configsFile`, or `tempConfigsFile`. It should be a name, not a verb.

2022-08-25 11:08 UTC, mohnoor94 commented on openapi/src/main/resources/templates/eg-travel-sdk/pom.mustache
> +    <!-- TODO: Dynamically update RG Open World Core version -->
What is `RG`?

2022-08-28 08:00 UTC, anssari1 commented on .github/workflows/main.yml
> +      - name: Generate_SDK_Files
Split into two workflows to generate SDK and publish

2022-08-29 08:42 UTC, anssari1 approved these changes

2022-08-29 08:47 UTC, anssari1 approved these changes

2022-08-29 08:52 UTC, merged